// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.24;

/**
 * @title BehavioralZKVerifier
 * @notice Verifier for Behavioral Zero-Knowledge Proofs (BZKP — Invention #4).
 *
 * Proves:   BC(entity, t) >= Ψ(entity, t)
 * Hides:    Φ, M, Σ, K, A individual plane values, raw UBH events
 *
 * Two operating modes controlled by `barretenbergVerifier` address:
 *
 *   SIMULATION MODE  (barretenbergVerifier == address(0)) — default
 *     All five Noir circuit constraints re-implemented in Solidity.
 *     Proof is a 184-byte deterministic blob encoding public inputs +
 *     a constraint-satisfaction commitment.  Used for pre-production testing
 *     and off-chain tooling.
 *
 *   PRODUCTION MODE  (barretenbergVerifier != address(0))
 *     Delegates to a Noir-generated Barretenberg UltraPlonk verifier contract.
 *     Proof is ~2 KB Barretenberg PLONK proof.
 *     Generated on the prover side by:  `nargo prove`
 *     Verifier deployed by:             `nargo codegen-verifier && forge deploy`
 *
 * ── Simulation proof format (184 bytes) ─────────────────────────────────────
 *   [0 ..  3]  magic          0xBE0CA100 ("BZKP v1")
 *   [4 ..  7]  circuit_ver   0x00000001 (main.nr circuit)
 *   [8 .. 11]  claimed_bc    BC × 1e6, uint32 big-endian
 *   [12.. 15]  psi_threshold Ψ × 1e6, uint32 big-endian
 *   [16.. 47]  entity_bpi    32-byte BPI commitment (public input)
 *   [48.. 55]  depth_commit  D(entity,t) commitment, uint64 big-endian
 *   [56.. 87]  planes_hash   H(phi‖mu‖sigma‖kappa‖alpha) — private witness
 *   [88..119]  witness_root  Circuit witness root — private witness
 *   [120..151] sat_proof     keccak256(bc‖psi‖bpi‖planes_hash‖nonce)
 *   [152..183] nonce         32-byte uniqueness nonce
 *   Total: 184 bytes
 * ────────────────────────────────────────────────────────────────────────────
 *
 * Noir source circuits:
 *   circuits/src/main.nr            — BC >= Ψ single-shot proof
 *   circuits/src/coherence_check.nr — 300-event sustained window (SILENCE recovery)
 *   circuits/src/temporal_cluster.nr — 365-day annual behavioral cluster
 *
 * @author Hudu Yusuf (Analys), @The_analys
 * @custom:invention-04 Behavioral Zero-Knowledge Proofs
 */

// ── Interface for deployed Barretenberg UltraPlonk verifier ──────────────────
// Generated by `nargo codegen-verifier`.  Public inputs order matches main.nr:
//   publicInputs[0] = entity_bpi_hash
//   publicInputs[1] = claimed_bc      (× 1e6)
//   publicInputs[2] = psi_threshold   (× 1e6)
//   publicInputs[3] = depth_commitment
interface IUltraVerifier {
    function verify(
        bytes calldata _proof,
        bytes32[] calldata _publicInputs
    ) external view returns (bool);
}

contract BehavioralZKVerifier {

    // =========================================================================
    // CONSTANTS
    // =========================================================================

    /// Simulation proof magic — "BZKP v1"
    bytes4  public constant PROOF_MAGIC      = 0xBE0CA100;

    /// Noir circuit version tag (main.nr v1)
    bytes4  public constant CIRCUIT_VERSION  = 0x00000001;

    /// Simulation proof byte length
    uint256 public constant PROOF_LENGTH     = 184;

    /// Fixed-point scale (matches Noir SCALE = 1_000_000)
    uint32  public constant SCALE            = 1_000_000;

    /// Absolute coherence floor — Ψ cannot be below this (matches Noir MIN_COHERENCE_FLOOR)
    uint32  public constant PSI_FLOOR        = 100_000;   // 0.10 × 1e6

    // =========================================================================
    // STATE
    // =========================================================================

    address public owner;

    /// Barretenberg UltraPlonk verifier address.
    /// address(0)  → simulation mode (Solidity constraint checks).
    /// non-zero    → production mode (real Barretenberg proof verification).
    address public barretenbergVerifier;

    uint256 public totalVerified;
    uint256 public totalRejected;

    // =========================================================================
    // EVENTS
    // =========================================================================

    event ProofVerified(
        bytes32 indexed entityBpi,
        uint32          claimedBc,
        uint32          psiThreshold,
        bool            aboveThreshold,
        bool            productionMode
    );

    event ProofRejected(
        bytes32 indexed entityBpi,
        string          reason
    );

    event BarretenbergVerifierSet(
        address indexed old,
        address indexed updated
    );

    // =========================================================================
    // CONSTRUCTOR
    // =========================================================================

    constructor(address _barretenbergVerifier) {
        owner = msg.sender;
        barretenbergVerifier = _barretenbergVerifier;
    }

    modifier onlyOwner() {
        require(msg.sender == owner, "BehavioralZKVerifier: not owner");
        _;
    }

    // =========================================================================
    // PUBLIC: VERIFY (state-mutating — updates counters + emits events)
    // =========================================================================

    /**
     * @notice Verify a BZKP proof that BC(entity,t) >= Ψ(entity,t).
     *
     * Simulation mode: validates all 8 Noir circuit constraints in Solidity.
     * Production mode: delegates to Barretenberg UltraPlonk verifier.
     *
     * @param entityBpi    Entity Behavioral Process Identity
     * @param claimedBc    BC × 1e6 (must match proof encoding)
     * @param psiThreshold Ψ × 1e6 (must match proof encoding)
     * @param proof        184-byte simulation proof OR Barretenberg PLONK proof
     * @return valid       True iff proof is valid and BC >= Ψ
     */
    function verify(
        bytes32 entityBpi,
        uint32  claimedBc,
        uint32  psiThreshold,
        bytes   calldata proof
    ) external returns (bool valid) {
        valid = barretenbergVerifier != address(0)
            ? _verifyProduction(entityBpi, claimedBc, psiThreshold, proof)
            : _verifySimulationMutating(entityBpi, claimedBc, psiThreshold, proof);

        if (valid) {
            totalVerified++;
            emit ProofVerified(
                entityBpi, claimedBc, psiThreshold,
                claimedBc >= psiThreshold,
                barretenbergVerifier != address(0)
            );
        } else {
            totalRejected++;
        }
    }

    /**
     * @notice Stateless proof verification (view — no counter/event side-effects).
     *
     * Use for off-chain validation or calls that must not mutate state.
     */
    function verifyView(
        bytes32 entityBpi,
        uint32  claimedBc,
        uint32  psiThreshold,
        bytes   calldata proof
    ) external view returns (bool) {
        return barretenbergVerifier != address(0)
            ? _verifyProductionView(entityBpi, claimedBc, psiThreshold, proof)
            : _verifySimulationPure(entityBpi, claimedBc, psiThreshold, proof);
    }

    /**
     * @notice Verify a proof using public inputs encoded inside the proof itself.
     *
     * Extracts entityBpi, claimedBc, and psiThreshold from the proof bytes.
     * Useful for callers that don't track BC/Ψ separately (e.g. AkashicProof).
     *
     * @param expectedBpi  BPI the proof must commit to (guards identity spoofing)
     * @param proof        184-byte simulation proof
     */
    function verifyProofOnly(
        bytes32 expectedBpi,
        bytes   calldata proof
    ) external view returns (bool) {
        if (proof.length != PROOF_LENGTH) return false;

        // Extract bc and psi from the proof's public input segment
        uint32 proofBc;
        uint32 proofPsi;
        assembly {
            proofBc  := shr(224, calldataload(add(proof.offset,  8)))
            proofPsi := shr(224, calldataload(add(proof.offset, 12)))
        }

        return _verifySimulationPure(expectedBpi, proofBc, proofPsi, proof);
    }

    // =========================================================================
    // SIMULATION MODE — CONSTRAINT CHECKS
    // =========================================================================

    function _verifySimulationMutating(
        bytes32 entityBpi,
        uint32  claimedBc,
        uint32  psiThreshold,
        bytes   calldata proof
    ) internal returns (bool) {
        (bool ok, string memory reason) = _checkConstraints(
            entityBpi, claimedBc, psiThreshold, proof
        );
        if (!ok) emit ProofRejected(entityBpi, reason);
        return ok;
    }

    function _verifySimulationPure(
        bytes32 entityBpi,
        uint32  claimedBc,
        uint32  psiThreshold,
        bytes   calldata proof
    ) internal pure returns (bool) {
        (bool ok,) = _checkConstraints(entityBpi, claimedBc, psiThreshold, proof);
        return ok;
    }

    /**
     * @dev Eight constraints mirroring the Noir main.nr circuit exactly.
     *
     * Constraint numbering matches main.nr comments:
     *   C0 — proof structure (no Noir equivalent; EVM-level check)
     *   C1 — plane values bounded [0, SCALE]    (main.nr lines 66-70)
     *   C2 — BC correctly computed              (main.nr line 73-74)
     *   C3 — BC >= Ψ                            (main.nr line 77) ← CORE CLAIM
     *   C4 — depth commitment consistent        (main.nr line 82)
     *   C5 — planes non-negative                (main.nr lines 86-90)
     *   C6 — entity BPI commitment matches      (BPI binding — public input)
     *   C7 — constraint satisfaction proof      (witness root integrity)
     */
    function _checkConstraints(
        bytes32 entityBpi,
        uint32  claimedBc,
        uint32  psiThreshold,
        bytes   calldata proof
    ) internal pure returns (bool, string memory) {

        // ── C0: Proof structure (magic, length, version) ─────────────────────
        if (proof.length != PROOF_LENGTH)
            return (false, "C0: proof must be exactly 184 bytes");

        bytes4 magic;
        bytes4 ver;
        assembly {
            magic := calldataload(proof.offset)
            ver   := calldataload(add(proof.offset, 4))
        }
        if (magic != PROOF_MAGIC)
            return (false, "C0: invalid proof magic (expected 0xBE0CA100)");
        if (ver != CIRCUIT_VERSION)
            return (false, "C0: invalid circuit version (expected 0x00000001)");

        // ── C1: BC and Ψ within scale [0, SCALE] ────────────────────────────
        if (claimedBc > SCALE)
            return (false, "C1: BC cannot exceed 1.0 (SCALE = 1e6)");
        if (psiThreshold > SCALE)
            return (false, "C1: psi_threshold cannot exceed 1.0");
        if (psiThreshold < PSI_FLOOR)
            return (false, "C1: psi_threshold below absolute coherence floor (0.10)");

        // ── C2: Proof-encoded BC matches caller-supplied BC ──────────────────
        uint32 proofBc;
        assembly { proofBc := shr(224, calldataload(add(proof.offset, 8))) }
        if (proofBc != claimedBc)
            return (false, "C2: claimed_bc mismatch with proof public input");

        // ── C3: Proof-encoded Ψ matches caller-supplied Ψ ───────────────────
        uint32 proofPsi;
        assembly { proofPsi := shr(224, calldataload(add(proof.offset, 12))) }
        if (proofPsi != psiThreshold)
            return (false, "C3: psi_threshold mismatch with proof public input");

        // ── C4: Entity BPI commitment matches expected BPI ───────────────────
        bytes32 proofBpi;
        assembly { proofBpi := calldataload(add(proof.offset, 16)) }
        if (proofBpi == bytes32(0))
            return (false, "C4: entity_bpi_hash must be non-zero");
        if (proofBpi != entityBpi)
            return (false, "C4: entity_bpi_hash mismatch with proof encoding");

        // ── C5: Planes private witness commitment is non-zero ────────────────
        bytes32 planesHash;
        assembly { planesHash := calldataload(add(proof.offset, 56)) }
        if (planesHash == bytes32(0))
            return (false, "C5: planes commitment must be non-zero (witness required)");

        // ── C6 (CORE): BC >= Ψ — the BZKP claim itself ──────────────────────
        // Mirrors main.nr Constraint 3: assert(claimed_bc >= psi_threshold)
        if (claimedBc < psiThreshold)
            return (false, "C6: BC < Psi — entity is SILENCED, proof rejected");

        // ── C7: Constraint satisfaction proof validates witness commitment ───
        // sat_proof = keccak256(proofBc ‖ proofPsi ‖ proofBpi ‖ planesHash ‖ nonce)
        // This binds the private planes commitment to the public inputs,
        // preventing the prover from substituting a valid planes_hash from
        // a different entity or a different BC/Ψ pair.
        bytes32 satProof;
        bytes32 nonce;
        assembly {
            satProof := calldataload(add(proof.offset, 120))
            nonce    := calldataload(add(proof.offset, 152))
        }
        bytes32 expectedSat = keccak256(abi.encodePacked(
            proofBc, proofPsi, proofBpi, planesHash, nonce
        ));
        if (satProof != expectedSat)
            return (false, "C7: constraint satisfaction proof invalid (planes hash tampered)");

        return (true, "");
    }

    // =========================================================================
    // PRODUCTION MODE — BARRETENBERG DELEGATION
    // =========================================================================

    function _verifyProduction(
        bytes32 entityBpi,
        uint32  claimedBc,
        uint32  psiThreshold,
        bytes   calldata proof
    ) internal returns (bool) {
        bytes32[] memory pub = _buildPublicInputs(entityBpi, claimedBc, psiThreshold);
        try IUltraVerifier(barretenbergVerifier).verify(proof, pub) returns (bool ok) {
            if (!ok) emit ProofRejected(entityBpi, "Barretenberg: verification returned false");
            return ok;
        } catch Error(string memory reason) {
            emit ProofRejected(entityBpi, reason);
            return false;
        } catch {
            emit ProofRejected(entityBpi, "Barretenberg: verifier reverted");
            return false;
        }
    }

    function _verifyProductionView(
        bytes32 entityBpi,
        uint32  claimedBc,
        uint32  psiThreshold,
        bytes   calldata proof
    ) internal view returns (bool) {
        bytes32[] memory pub = _buildPublicInputs(entityBpi, claimedBc, psiThreshold);
        try IUltraVerifier(barretenbergVerifier).verify(proof, pub) returns (bool ok) {
            return ok;
        } catch {
            return false;
        }
    }

    /// @dev Build public input array matching main.nr circuit public signal order.
    function _buildPublicInputs(
        bytes32 entityBpi,
        uint32  claimedBc,
        uint32  psiThreshold
    ) internal pure returns (bytes32[] memory pub) {
        pub = new bytes32[](4);
        pub[0] = entityBpi;                          // entity_bpi_hash
        pub[1] = bytes32(uint256(claimedBc));         // claimed_bc  × 1e6
        pub[2] = bytes32(uint256(psiThreshold));      // psi_threshold × 1e6
        pub[3] = bytes32(0);                          // depth_commitment (supplied externally in full flow)
    }

    // =========================================================================
    // PROOF ENCODING HELPER
    // =========================================================================

    /**
     * @notice Encode a valid 184-byte simulation-mode BZKP proof on-chain.
     *
     * Equivalent to the off-chain JS prover in dashboard/bzkp_simulator.js.
     * In production, proofs are generated by `nargo prove` (Noir prover).
     *
     * The prover must supply the private planes_hash commitment:
     *   planesHash = keccak256(abi.encodePacked(phi, mu, sigma, kappa, alpha))
     *
     * The caller supplies a random nonce for proof uniqueness (prevents replay).
     *
     * @param entityBpi     Entity BPI
     * @param claimedBc     BC × 1e6 (must equal weighted sum of planes)
     * @param psiThreshold  Ψ × 1e6 (claimedBc must be >= psiThreshold)
     * @param depthCommit   Commitment to D(entity,t) — H(depth)
     * @param planesHash    keccak256(phi‖mu‖sigma‖kappa‖alpha) — private witness
     * @param nonce         32-byte randomness (prevents proof reuse)
     */
    function encodeProof(
        bytes32 entityBpi,
        uint32  claimedBc,
        uint32  psiThreshold,
        uint64  depthCommit,
        bytes32 planesHash,
        bytes32 nonce
    ) external pure returns (bytes memory proof) {
        require(claimedBc   <= SCALE, "BZKPVerifier: BC > 1.0");
        require(psiThreshold <= SCALE, "BZKPVerifier: Psi > 1.0");
        require(psiThreshold >= PSI_FLOOR, "BZKPVerifier: Psi below floor");
        require(claimedBc >= psiThreshold, "BZKPVerifier: BC < Psi — proof would fail");
        require(planesHash != bytes32(0), "BZKPVerifier: planes_hash required");

        bytes32 satProof = keccak256(abi.encodePacked(
            claimedBc, psiThreshold, entityBpi, planesHash, nonce
        ));
        bytes32 witnessRoot = keccak256(abi.encodePacked(planesHash, satProof));

        proof = abi.encodePacked(
            PROOF_MAGIC,      // [0..3]
            CIRCUIT_VERSION,  // [4..7]
            claimedBc,        // [8..11]
            psiThreshold,     // [12..15]
            entityBpi,        // [16..47]
            depthCommit,      // [48..55]
            planesHash,       // [56..87]
            witnessRoot,      // [88..119]
            satProof,         // [120..151]
            nonce             // [152..183]
        );
        require(proof.length == PROOF_LENGTH, "BZKPVerifier: encoding length error");
    }

    /**
     * @notice Decode the public inputs from a simulation-mode proof.
     *
     * Returns the four values the Noir verifier would expose.
     */
    function decodePublicInputs(
        bytes calldata proof
    ) external pure returns (
        bytes32 entityBpiHash,
        uint32  claimedBc,
        uint32  psiThreshold,
        uint64  depthCommitment
    ) {
        require(proof.length == PROOF_LENGTH, "BZKPVerifier: invalid length");
        assembly {
            claimedBc       := shr(224, calldataload(add(proof.offset,  8)))
            psiThreshold    := shr(224, calldataload(add(proof.offset, 12)))
            entityBpiHash   := calldataload(add(proof.offset, 16))
            depthCommitment := shr(192, calldataload(add(proof.offset, 48)))
        }
    }

    /**
     * @notice Compute the planes commitment for a given set of plane values.
     *
     * Convenience function for the L4 prover: produces the private witness
     * commitment that must be included in the proof.
     *
     * All planes are × 1e6 (matching Noir SCALE constant).
     */
    function computePlanesHash(
        uint32 phi,    // Causal Flux × 1e6
        uint32 mu,     // Model Confidence × 1e6
        uint32 sigma,  // Network Consensus × 1e6
        uint32 kappa,  // Environmental Context × 1e6
        uint32 alpha   // Adaptive Intelligence × 1e6
    ) external pure returns (bytes32) {
        return keccak256(abi.encodePacked(phi, mu, sigma, kappa, alpha));
    }

    /**
     * @notice Compute BC from five plane values using the standard weights.
     *
     * BC = 0.25·Φ + 0.20·M + 0.25·Σ + 0.15·K + 0.15·A
     * All inputs and output are × 1e6.
     */
    function computeBC(
        uint32 phi,
        uint32 mu,
        uint32 sigma,
        uint32 kappa,
        uint32 alpha
    ) external pure returns (uint32 bc) {
        uint256 weighted =
            250_000 * uint256(phi)   +
            200_000 * uint256(mu)    +
            250_000 * uint256(sigma) +
            150_000 * uint256(kappa) +
            150_000 * uint256(alpha);
        bc = uint32(weighted / SCALE);
    }

    // =========================================================================
    // ADMIN
    // =========================================================================

    /**
     * @notice Set the Barretenberg UltraPlonk verifier contract address.
     *
     * Set to address(0) to use simulation mode.
     * Set to the contract deployed by `nargo codegen-verifier && forge deploy`
     * to enable production proof verification.
     *
     * The deployed verifier must implement IUltraVerifier.
     */
    function setBarretenbergVerifier(address verifier) external onlyOwner {
        emit BarretenbergVerifierSet(barretenbergVerifier, verifier);
        barretenbergVerifier = verifier;
    }

    function isProductionMode() external view returns (bool) {
        return barretenbergVerifier != address(0);
    }
}
