// gRPC service implementation for the AXIOM Node interface.
// Exposes: EmitEvent, GetTruthState, GetResonanceVector, RoutePacket, StreamEvents

package rcp

import (
	"context"
	"time"

	"go.uber.org/zap"
)

// AXIOMNodeServer is the gRPC service interface (generated from proto/ubh.proto).
// This is a hand-written stub matching the proto definition until protoc generates it.

// EmitEventRequest models the gRPC EmitEvent request.
type EmitEventRequest struct {
	EntityBpi   []byte
	EventType   int32
	Payload     []byte
	BcAtEvent   float32
	DepthAtEvent float64
}

// EmitEventResponse models the gRPC EmitEvent response.
type EmitEventResponse struct {
	SelfHash  []byte
	Accepted  bool
	ErrorMsg  string
}

// GetTruthStateRequest models the GetTruthState request.
type GetTruthStateRequest struct {
	EntityBpi []byte
}

// GetTruthStateResponse models the GetTruthState response.
type GetTruthStateResponse struct {
	Bpi       []byte
	Bc        float32
	Psi       float32
	Depth     float64
	Love      float32
	Xi        float64
	IsSilenced bool
}

// RoutePacketRequest models the RoutePacket request.
type RoutePacketRequest struct {
	SenderBpi   []byte
	ReceiverBpi []byte
	Payload     []byte
	Ttl         int32
	Timestamp   int64
}

// RoutePacketResponse models the RoutePacket response.
type RoutePacketResponse struct {
	Delivered   bool
	NextHopBpi  []byte
	Resonance   float32
	ErrorMsg    string
}

// RegisterAXIOMNodeServer registers the gRPC server (simplified stub).
func RegisterAXIOMNodeServer(server interface{}, daemon *RCPDaemon) {
	// In production: generated by protoc-gen-go-grpc
	// grpc_server.RegisterAXIOMNodeServer(server.(*grpc.Server), daemon)
	daemon.logger.Info("AXIOM Node gRPC service registered")
}

// EmitEvent handles behavioral event submission.
func (d *RCPDaemon) EmitEvent(ctx context.Context, req *EmitEventRequest) (*EmitEventResponse, error) {
	d.logger.Debug("EmitEvent",
		zap.Binary("entity_bpi", req.EntityBpi[:min(len(req.EntityBpi), 8)]),
		zap.Int32("event_type", req.EventType),
	)

	// In production: validate, write to Akashic Index, trigger coherence update
	return &EmitEventResponse{
		SelfHash: make([]byte, 32),
		Accepted: true,
	}, nil
}

// GetTruthState returns Ξ(entity, t) truth state.
func (d *RCPDaemon) GetTruthState(ctx context.Context, req *GetTruthStateRequest) (*GetTruthStateResponse, error) {
	d.mu.RLock()
	bc := d.localBC
	psi := d.localPsi
	d.mu.RUnlock()

	return &GetTruthStateResponse{
		Bpi:        req.EntityBpi,
		Bc:         bc,
		Psi:        psi,
		Depth:      0.0,  // Query Akashic Index in production
		Love:       1.0,
		Xi:         0.0,  // Compute from master equation
		IsSilenced: bc < psi,
	}, nil
}

// RoutePacket handles RCP packet routing.
func (d *RCPDaemon) RoutePacket(ctx context.Context, req *RoutePacketRequest) (*RoutePacketResponse, error) {
	var senderBPI, receiverBPI [32]byte
	copy(senderBPI[:], req.SenderBpi)
	copy(receiverBPI[:], req.ReceiverBpi)

	packet := &RCPPacket{
		SenderBPI:   senderBPI,
		ReceiverBPI: receiverBPI,
		TTL:         uint8(req.Ttl),
		Payload:     req.Payload,
		Timestamp:   req.Timestamp,
		SenderBC:    d.localBC,
	}

	err := d.Route(packet)
	if err != nil {
		return &RoutePacketResponse{
			Delivered: false,
			ErrorMsg:  err.Error(),
		}, nil
	}

	return &RoutePacketResponse{
		Delivered: true,
		Resonance: d.ComputeResonance(receiverBPI),
	}, nil
}

// GetResonanceVector returns the local RF vector.
func (d *RCPDaemon) GetResonanceVector(ctx context.Context, bpi []byte) ([RFVectorDim]float32, error) {
	d.mu.RLock()
	defer d.mu.RUnlock()
	return d.localRF, nil
}

// HealthCheck returns daemon health status.
func (d *RCPDaemon) HealthCheck(ctx context.Context) map[string]interface{} {
	connected := d.ConnectedPeers()
	metrics := d.Metrics()
	return map[string]interface{}{
		"status":           "healthy",
		"local_bc":         d.localBC,
		"local_psi":        d.localPsi,
		"is_silenced":      d.localBC < d.localPsi,
		"connected_peers":  len(connected),
		"packets_routed":   metrics["packets_routed"],
		"packets_dropped":  metrics["packets_dropped"],
		"uptime":           time.Now().String(),
	}
}

func min(a, b int) int {
	if a < b { return a }
	return b
}
